package com.saurav.JobService.dto;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.time.Instant;
import java.util.UUID;


@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class JobDto {
    private UUID userId;            // user_id is now a UUID, which is provided as String from the user
    private UUID jobId;             // job_id will be generated by the backend
    private boolean isRecurring;    // Whether the job is recurring
    private String interval;        // The interval (if applicable, like "daily", "weekly")
    private int maxRetryCount;      // Max retry count for the job
    private Instant createdTime;    // Timestamp of when the job was created

}
